version: '3'
services:
  postgres:
    image: "postgres:12"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=db
    volumes:
      - "/docker/pg_data:/var/lib/postgresql/data"
    restart: "always"

  redis:
    image: "redis:5.0"

  celery:
    build: ./celery
    environment:
      - CELERY_BROKER_URL=redis://redis:6379
      - CELERY_RESULT_BACKEND=redis://redis:6379
    depends_on:
      - redis
    links:
      - redis
    restart: "always"

  flask:
    build: ./service
    ports:
      - "6000:6000"
    environment:
      - CELERY_BROKER_URL=redis://redis:6379
      - CELERY_RESULT_BACKEND=redis://redis:6379
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB=db
    depends_on:
      - redis
      - postgres
      - celery
    links:
      - redis
      - postgres
    restart: "always"
